// NOTE: this file is auto-generated by scripts/regen-version.py
//       and should not be modified directly.
//       it is only committed for easier distribution,
//       to regenerate the file use 'make regen-version'
//       or run the script directly.
#pragma once

#include <elash/defs/stringify.h>
#include <elash/defs/semver.h>
#include <elash/defs/sv.h>

#define EL_VERSION_MAJOR 0
#define EL_VERSION_MINOR 1
#define EL_VERSION_PATCH 2

// NOTE: parentheses are intentionally omitted so further
//       compile-time string concatenation is possible
#define EL_VERSION_STRING \
    EL_STRINGIFY(EL_VERSION_MAJOR) "." \
    EL_STRINGIFY(EL_VERSION_MINOR) "." \
    EL_STRINGIFY(EL_VERSION_PATCH)

#define EL_VERSION_SEMVER   \
    EL_SEM_VER(             \
        (EL_VERSION_MAJOR), \
        (EL_VERSION_MINOR), \
        (EL_VERSION_PATCH)  \
    )

// encoding version as a single integer for easy comparison
// for example: 1.2.3 -> 001002003
#define EL_VERSION_ENCODE(MAJOR, MINOR, PATCH) \
    (((MAJOR) * 1000000UL) + ((MINOR) * 1000UL) + (PATCH))

#define EL_VERSION_CODE \
    EL_VERSION_ENCODE(EL_VERSION_MAJOR, EL_VERSION_MINOR, EL_VERSION_PATCH)

// checking version at compile time
#define EL_VERSION_AT_LEAST(MAJOR, MINOR, PATCH) \
    (EL_VERSION_CODE >= EL_VERSION_ENCODE(MAJOR, MINOR, PATCH))

#define EL_VERSION_EXACT(MAJOR, MINOR, PATCH) \
    (EL_VERSION_CODE == EL_VERSION_ENCODE(MAJOR, MINOR, PATCH))

#define EL_VERSION_BEFORE(MAJOR, MINOR, PATCH) \
    (EL_VERSION_CODE < EL_VERSION_ENCODE(MAJOR, MINOR, PATCH))

// runtime getters
ElSemVersion el_library_version();
ElStringView el_library_version_string();
