#pragma once

typedef enum ElSrcDocStatus {
    EL_SRCDOC_ERR_SUCCESS,

    EL_SRCDOC_ERR_FOPEN_FAILED,
    EL_SRCDOC_ERR_FTELL_FAILED,
    EL_SRCDOC_ERR_FREAD_FAILED,
    EL_SRCDOC_ERR_FWRITE_FAILED,
} ElSrcDocStatus;

