from string import Template
from pathlib import Path

import subprocess
import argparse
import typing
import sys

from dataclasses import dataclass

@dataclass(frozen=True)
class SemVer:
    major: int
    minor: int
    patch: int

    @staticmethod
    def parse(text: str) -> SemVer:
        parts = text.strip().split(".")
        if len(parts) != 3:
            raise ValueError

        try:
            major, minor, patch = (int(part) for part in parts)
        except ValueError:
            raise ValueError

        if major < 0 or minor < 0 or patch < 0:
            raise ValueError

        return SemVer(major, minor, patch)

class CliArgs(argparse.Namespace):
    version_file: str
    input:  str
    output: str

def eprint(*args, **kwargs):
    print(*args, **kwargs, file=sys.stderr)

def get_commit_sha() -> str:
    try:
        commit = subprocess.run(
            ["git", "rev-parse", "--short=8", "HEAD"],
            capture_output=True,
            text=True,
            check=True
        ).stdout.strip()

        status = subprocess.run(
            ["git", "status", "--porcelain"],
            capture_output=True,
            text=True,
            check=True
        ).stdout.strip()

        if status:
            commit += "-dirty"

        return commit
    except (subprocess.SubprocessError, FileNotFoundError):
        return "none"

def main() -> int:
    parser = argparse.ArgumentParser(
        prog='regen-version',
        description='Regenerate the version.h header file from a template'
    )

    parser.add_argument('version_file',   nargs='?', default='VERSION', help='the version file path')
    parser.add_argument('-i', '--input',  default='version.h.in',       help='the input template path')
    parser.add_argument('-o', '--output', required=True,                help='the output header path')
    args = typing.cast(CliArgs, parser.parse_args())

    version_file = Path(args.version_file)
    if not version_file.is_file():
        eprint("Provided version file does not exist or isn't a file")
        return 1

    try:
        version = SemVer.parse(version_file.read_text())
    except ValueError:
        eprint("Provided version file doesn't contain a valid semantic version")
        return 1

    input_file = Path(args.input)
    if not input_file.is_file():
        eprint("Provided teplate file does not exist or isn't a file")
        return 1

    template = Template(input_file.read_text())
    try:
        vars: dict = {
            "MAJOR": version.major,
            "MINOR": version.minor,
            "PATCH": version.patch,
            "COMMIT": get_commit_sha(),
        }

        output = f"""\
// NOTE: this file is auto-generated by scripts/regen-version.py
//       and should not be modified directly.
//       it is only committed for easier distribution,
//       to regenerate the file use 'make regen-version'
//       or run the script directly.
{template.substitute(vars)}"""

    except KeyError as e:
        eprint(e)
        return 2

    output_file = Path(args.output)
    output_file.write_text(output)

    return 0

if __name__ == '__main__':
    sys.exit(main())
