name: CI on Linux ARM64

permissions:
  contents: read

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  run-ci:
    runs-on: ubuntu-24.04-arm
    env:
      EXTRA_CFLAGS: -DELC_SHOW_BACKTRACE=0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Cache ccache
        uses: actions/cache@v6
        with:
          path: ~/.cache/ccache
          key: ${{ runner.os }}-${{ runner.arch }}-ccache-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-ccache-${{ github.ref_name }}-
            ${{ runner.os }}-${{ runner.arch }}-ccache-

      - name: Run CI inside container
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:${{ github.workspace }}" \
            -v "${HOME}/.cache/ccache:/ccache" \
            -w "${{ github.workspace }}" \
            -e CC="ccache cc" \
            -e CCACHE_DIR="/ccache" \
            "ghcr.io/${{ github.repository_owner }}/elash-ci-arm64:latest" \
            sh -c "ccache -z && make libelash-static elc -j\$(nproc) && ccache -s && \
            make unit-test && make test-e2e-verbose && make test-unparser-verbose && make test-fuzz-1000"

      - name: Archive
        if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:${{ github.workspace }}" \
            -w "${{ github.workspace }}" \
            "ghcr.io/${{ github.repository_owner }}/elash-ci-arm64:latest" \
            make archive

      - name: Find Release File
        if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
        id: locate_file
        run: echo "archive=$(ls out/release/*-release.tar.gz | head -n 1)" >> "$GITHUB_OUTPUT"

      - name: Upload Artifact
        if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: ${{ steps.locate_file.outputs.archive }}
          if-no-files-found: error
