name: CI on MacOS ARM64

permissions:
  contents: read

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  run-ci:
    runs-on: macos-latest
    env:
      CC: ccache clang
      LLVM_CONFIG: /opt/homebrew/opt/llvm/bin/llvm-config

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install dependencies
        run: brew install llvm ccache criterion

      - name: Set Environment
        run: |
          echo "EXTRA_CFLAGS=-I$(brew --prefix)/include" >> $GITHUB_ENV
          echo "EXTRA_LDFLAGS=-L$(brew --prefix)/lib" >> $GITHUB_ENV
          echo "EXTRA_TESTS_CFLAGS=-I$(brew --prefix)/include" >> $GITHUB_ENV
          echo "EXTRA_TESTS_LDFLAGS=-L$(brew --prefix)/lib" >> $GITHUB_ENV

      - name: Ensure ccache directory
        run: mkdir -p ~/.ccache

      - name: Cache ccache
        uses: actions/cache@v6
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-${{ runner.arch }}-ccache-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-ccache-${{ github.ref_name }}-
            ${{ runner.os }}-${{ runner.arch }}-ccache-

      - name: Zero ccache stats
        run: ccache -z

      - name: Build
        run: make libelash-static elc -j$(sysctl -n hw.ncpu)

      - name: Show ccache stats
        run: ccache -s

      - name: Unit tests
        run: make unit-test

      - name: End-to-End tests
        run: make test-e2e-verbose

      - name: Unparser tests
        run: make test-unparser-verbose

      - name: Fuzz tests
        run: make test-fuzz

      - name: Archive
        if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
        run: make archive

      - name: Find Release File
        if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
        id: locate_file
        run: echo "archive=$(ls out/release/*-release.tar.gz | head -n 1)" >> "$GITHUB_OUTPUT"

      - name: Upload Artifact
        if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: ${{ steps.locate_file.outputs.archive }}
          if-no-files-found: error
