name: CI on Windows X64

permissions:
  contents: read

on:
  pull_request:
    branches:
      - '**'
  push:
    tags:
      - '**'
  workflow_dispatch:

jobs:
  run-ci:
    runs-on: windows-latest
    env:
      CC: ccache gcc
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      EXTRA_CFLAGS: -DELC_SHOW_BACKTRACE=0
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup MSYS2 and MinGW
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            base-devel
            mingw-w64-ucrt-x86_64-toolchain
            mingw-w64-ucrt-x86_64-ccache
            mingw-w64-ucrt-x86_64-llvm

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "21.1"

      - name: Ensure ccache directory
        run: mkdir -p "${GITHUB_WORKSPACE}/.ccache"

      - name: Cache ccache
        uses: actions/cache@v6
        with:
          path: ${{ github.workspace }}/.ccache
          key: ${{ runner.os }}-${{ runner.arch }}-ccache-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-ccache-${{ github.ref_name }}-
            ${{ runner.os }}-${{ runner.arch }}-ccache-

      - name: Zero ccache stats
        run: ccache -z

      - name: Build
        run: make libelash-static elc -j$(nproc)

      - name: Show ccache stats
        run: ccache -s

      # i have no idea how to install criterion in this environment
      # we have like two unit tests that actually doesnt test anything
      # anyway so let's just skip this step; e2e test are more important
      #- name: Unit tests
      #  run: make unit-test

      - name: End-to-End tests
        run: make test-e2e-verbose

      - name: Unparser tests
        run: make test-unparser-verbose

      - name: Fuzz tests
        run: make test-fuzz

      - name: Archive
        if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
        run: make archive

      - name: Find Release File
        if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
        id: locate_file
        run: echo "archive=$(ls out/release/*-release.tar.gz | head -n 1)" >> "$GITHUB_OUTPUT"

      - name: Upload Artifact
        if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: ${{ steps.locate_file.outputs.archive }}
          if-no-files-found: error
