name: Dev CI

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CC: ccache cc
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y llvm libcriterion-dev ccache

      - name: Cache ccache
        uses: actions/cache@v6
        with:
          path: ~/.cache/ccache
          key: ${{ runner.os }}-ccache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      - name: Zero ccache stats
        run: ccache -z

      - name: Build
        run: make libelash-static elc -j$(nproc)

      - name: Show ccache stats
        run: ccache -s

      - name: Unit tests
        run: make unit-test

      - name: End-to-End tests
        run: make test-e2e
